# -*- coding: utf-8 -*-
"""LAB_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjBgBNVMEloykAmTQI909uelcCGkf89_
"""

!pip install numpy

"""#  **Task 1: Lists**



"""

#Create a list of 10 Integers?
numbers = [1,2,3,4,5,6,7,8,9,10]
print('List of Ten Integers is', numbers)

#Find sum,max,min
print('Sum',sum(numbers))
print('MAX',max(numbers))
print('MIN',min(numbers))

#Add and Remove
numbers.append(20)
numbers.remove(2)
print('Updated List',numbers)

#Acending and Decending Order
print('Acending',sorted(numbers))
print('Decending',sorted(numbers, reverse =True))

"""# **Task 2: Tuples**

"""

# Create a tuple of 5 Strings
fruits = ('apple','Banana','cherry','mango','grape')
print('Second element', fruits[1])
print('Last one', fruits[-1])

# convert tuple into list
fruits_list = list(fruits)
fruits_list[2] = 'orange'
print('Modified', fruits_list)

"""# **Task 3: Sets**

"""

#two set with unique elements

set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

# uniion and intersection

print('union', set_a | set_b)
print('Intersection', set_a & set_b)
print('Differnce', set_a - set_b)

"""# **Task 4: Dictionaries**

"""

# creta 5 unique Keys
students = {'Ali': 85,'Salman':90,'Rehman':30,'Yawar':40}

print('Keys', students.keys())
print('Values', students.values())

"""# **Task 5: Numpay**

# **Task 6: Matplotlib**
"""